apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-golang-app1
  namespace: default
  labels:
    app: my-golang-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-golang-app1
  template:
    metadata:
      labels:
        app: my-golang-app1
    spec:
      containers:
        - name: my-golang-app1
          image: us-central1-docker.pkg.dev/brave-attic-417321/gogo-bk/my-golang-app1:$COMMIT_SHA1
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 