apiVersion: v1
kind: Service
metadata:
  name: my-golang-app1
  namespace: default
  labels:
    app: my-golang-app1
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    name: my-golang-app1